[package]
name = "reality_kit"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bevy = { workspace = true }
reality_core = { path = "crates/reality_core" }
reality_player_interface = { path = "crates/reality_player_interface" }
serde.workspace = true
serde_json.workspace = true
strum = { workspace = true }
strum_macros = { workspace = true }

[workspace]
resolver = "2"

members = [
    "crates/*",
    # "examples/*"
]

[[example]]
name = "keyboard-config"
path = "examples/keyboard-config/client.rs"

[workspace.dependencies]
bevy = { version = "0.14.0" }
serde = "1.0.217"
serde_json = "1.0.135"
strum = "0.25"
strum_macros = "0.25"
